//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tourist_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serbian.
        /// </summary>
        internal static string _string {
            get {
                return ResourceManager.GetString("string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept review.
        /// </summary>
        internal static string AcceptReview {
            get {
                return ResourceManager.GetString("AcceptReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept tour.
        /// </summary>
        internal static string AcceptTour {
            get {
                return ResourceManager.GetString("AcceptTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept part of tour.
        /// </summary>
        internal static string AcceptTourPart {
            get {
                return ResourceManager.GetString("AcceptTourPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age structure.
        /// </summary>
        internal static string AgeStructure {
            get {
                return ResourceManager.GetString("AgeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvo.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call out.
        /// </summary>
        internal static string CallOut {
            get {
                return ResourceManager.GetString("CallOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist call out.
        /// </summary>
        internal static string CallOutTourists {
            get {
                return ResourceManager.GetString("CallOutTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel tour.
        /// </summary>
        internal static string CancelTour {
            get {
                return ResourceManager.GetString("CancelTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel tour?.
        /// </summary>
        internal static string CancelTourText {
            get {
                return ResourceManager.GetString("CancelTourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check checkpoint.
        /// </summary>
        internal static string CheckButton {
            get {
                return ResourceManager.GetString("CheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tačka na kojoj se priključio.
        /// </summary>
        internal static string CheckpointName {
            get {
                return ResourceManager.GetString("CheckpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoints:.
        /// </summary>
        internal static string Checkpoints {
            get {
                return ResourceManager.GetString("Checkpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City and Country:.
        /// </summary>
        internal static string CityAndCountry {
            get {
                return ResourceManager.GetString("CityAndCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tour.
        /// </summary>
        internal static string CreateTour {
            get {
                return ResourceManager.GetString("CreateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour for popular language.
        /// </summary>
        internal static string CreateTourForLanguage {
            get {
                return ResourceManager.GetString("CreateTourForLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour for popular location.
        /// </summary>
        internal static string CreateTourForLocation {
            get {
                return ResourceManager.GetString("CreateTourForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour from request.
        /// </summary>
        internal static string CreateTourFromRequest {
            get {
                return ResourceManager.GetString("CreateTourFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create part of complex tour.
        /// </summary>
        internal static string CreateTourPart {
            get {
                return ResourceManager.GetString("CreateTourPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkTheme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick tour date:.
        /// </summary>
        internal static string DatePick {
            get {
                return ResourceManager.GetString("DatePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range.
        /// </summary>
        internal static string DatesTable {
            get {
                return ResourceManager.GetString("DatesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline review.
        /// </summary>
        internal static string DeclineReview {
            get {
                return ResourceManager.GetString("DeclineReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionTable {
            get {
                return ResourceManager.GetString("DescriptionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissal.
        /// </summary>
        internal static string Dismissal {
            get {
                return ResourceManager.GetString("Dismissal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency end.
        /// </summary>
        internal static string EmergencyEnd {
            get {
                return ResourceManager.GetString("EmergencyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field mustn&apos;t be empty!.
        /// </summary>
        internal static string EmptyFieldText {
            get {
                return ResourceManager.GetString("EmptyFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDate.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of future tours.
        /// </summary>
        internal static string FutureTitle {
            get {
                return ResourceManager.GetString("FutureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future tours.
        /// </summary>
        internal static string FutureTours {
            get {
                return ResourceManager.GetString("FutureTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour History.
        /// </summary>
        internal static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History tours.
        /// </summary>
        internal static string HistoryTours {
            get {
                return ResourceManager.GetString("HistoryTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images:.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageTable {
            get {
                return ResourceManager.GetString("LanguageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationTable {
            get {
                return ResourceManager.GetString("LocationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum guests number:.
        /// </summary>
        internal static string MaxGuestsNumber {
            get {
                return ResourceManager.GetString("MaxGuestsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most requested.
        /// </summary>
        internal static string MostRequested {
            get {
                return ResourceManager.GetString("MostRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tourists.
        /// </summary>
        internal static string NumberOfTourists {
            get {
                return ResourceManager.GetString("NumberOfTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Report.
        /// </summary>
        internal static string PDFReport {
            get {
                return ResourceManager.GetString("PDFReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        internal static string PickedLanguage {
            get {
                return ResourceManager.GetString("PickedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit job.
        /// </summary>
        internal static string QuitJob {
            get {
                return ResourceManager.GetString("QuitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit your job?.
        /// </summary>
        internal static string QuitJobText {
            get {
                return ResourceManager.GetString("QuitJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request number.
        /// </summary>
        internal static string RequestNumber {
            get {
                return ResourceManager.GetString("RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests statistics.
        /// </summary>
        internal static string RequestsStat {
            get {
                return ResourceManager.GetString("RequestsStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review text.
        /// </summary>
        internal static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serbian.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour start at:.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tour.
        /// </summary>
        internal static string StartTour {
            get {
                return ResourceManager.GetString("StartTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of today tours.
        /// </summary>
        internal static string TodayTitle {
            get {
                return ResourceManager.GetString("TodayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today tours.
        /// </summary>
        internal static string TodayTours {
            get {
                return ResourceManager.GetString("TodayTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string TourDate {
            get {
                return ResourceManager.GetString("TourDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string TourDuration {
            get {
                return ResourceManager.GetString("TourDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourists between 18 and 50.
        /// </summary>
        internal static string TouristsBetween {
            get {
                return ResourceManager.GetString("TouristsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourists list.
        /// </summary>
        internal static string TouristsList {
            get {
                return ResourceManager.GetString("TouristsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourists older than 18.
        /// </summary>
        internal static string TouristsOlder {
            get {
                return ResourceManager.GetString("TouristsOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourists under 18.
        /// </summary>
        internal static string TouristsUnder {
            get {
                return ResourceManager.GetString("TouristsUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourists without voucher(%).
        /// </summary>
        internal static string TouristsWithoutVoucher {
            get {
                return ResourceManager.GetString("TouristsWithoutVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourists with voucher(%).
        /// </summary>
        internal static string TouristsWithVoucher {
            get {
                return ResourceManager.GetString("TouristsWithVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour live.
        /// </summary>
        internal static string TourLive {
            get {
                return ResourceManager.GetString("TourLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour name:.
        /// </summary>
        internal static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour reviews.
        /// </summary>
        internal static string TourReviews {
            get {
                return ResourceManager.GetString("TourReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UntilDate.
        /// </summary>
        internal static string UntilDate {
            get {
                return ResourceManager.GetString("UntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using voucher structure.
        /// </summary>
        internal static string UsingVoucherStructure {
            get {
                return ResourceManager.GetString("UsingVoucherStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited.
        /// </summary>
        internal static string Visited {
            get {
                return ResourceManager.GetString("Visited", resourceCulture);
            }
        }
    }
}
